//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAn
    {
        public BanAn()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int IDBanAn { get; set; }
        public string TenBan { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
