//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.TimeSpan> GioIn { get; set; }
        public Nullable<System.TimeSpan> GioOut { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhLuong TinhLuong { get; set; }
    }
}
