//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int IDHoaDon { get; set; }
        public System.DateTime NgayTaoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayKetThucHoaDon { get; set; }
        public int IDBanAn { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
    }
}
