//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThucAn
    {
        public LoaiThucAn()
        {
            this.ThucAns = new HashSet<ThucAn>();
        }
    
        public int IDLoaiThucAn { get; set; }
        public string TenLoaiThucAn { get; set; }
    
        public virtual ICollection<ThucAn> ThucAns { get; set; }
    }
}
