//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhLuong
    {
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<double> SoGioLam { get; set; }
        public Nullable<double> Luong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
    }
}
